
<project xmlns="http://maven.apache.org/POM/4.0.0">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hr</groupId>
    <artifactId>python-maven-app</artifactId>
    <version>1.0</version>

    <build>
        <plugins>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>

                <executions>

                    <!-- INSTALL DEPENDENCIES -->
                    <execution>
                        <id>install-deps</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>

                        <configuration>
                            <executable>python3</executable>
                            <arguments>
                                <argument>-m</argument>
                                <argument>pip</argument>
                                <argument>install</argument>
                                <argument>-r</argument>
                                <argument>requirements.txt</argument>
                            </arguments>
                        </configuration>
                    </execution>

                    <!-- RUN APP -->
                    <execution>
                        <id>run-app</id>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>

                        <configuration>
                            <executable>python3</executable>
                            <arguments>
                                <argument>app.py</argument>
                            </arguments>
                        </configuration>
                    </execution>

                </executions>

            </plugin>

        </plugins>
    </build>

</project>
