
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hr</groupId>
    <artifactId>python-maven-app</artifactId>
    <version>1.0</version>

    <build>
        <plugins>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>

                <executions>

                    <execution>
                        <id>install-deps</id>
                        <phase>generate-sources</phase>

                        <goals>
                            <goal>exec</goal>
                        </goals>

                        <configuration>
                            <executable>pip3</executable>

                            <arguments>
                                <argument>install</argument>
                                <argument>-r</argument>
                                <argument>requirements.txt</argument>
                            </arguments>

                        </configuration>
                    </execution>

                </executions>

            </plugin>

        </plugins>
    </build>

</project>
